Repository Lap343/2021-React-Apprenticeship, pull requests merged in 2021-07, with the labels that each got.

#44 making app mobile friendly
  movie-app/src/App.js
  movie-app/src/Components/MovieDetails.js
  movie-app/src/scss/components/body/_body.scss
  movie-app/src/scss/components/body/_card.scss
  movie-app/src/scss/components/body/_modal.scss
  movie-app/src/scss/components/body/_search_results.scss
  movie-app/src/scss/components/header/_header.scss
  movie-app/src/scss/components/header/_navigation.scss
  movie-app/src/scss/components/header/_searchbar.scss
Labels: enhancement

#49 feat(mobile-button-sizing):adjust-button-size-for-mobile
  movie-app/src/scss/components/body/_search_results.scss
Labels: enhancement

#50 Clean up code
  movie-app/src/App.css
  movie-app/src/App.js
  movie-app/src/Components/FeatCarousel.js
  movie-app/src/Components/Modal.js
  movie-app/src/Components/MovieCard.js
  movie-app/src/Components/MovieDetails.js
  movie-app/src/Components/StaffCarousel.js
  movie-app/src/body/Home.js
  movie-app/src/body/Searched.js
  movie-app/src/header/NavBar.js
  movie-app/src/header/Search_Icon.png
  movie-app/src/index.js
  movie-app/src/reportWebVitals.js
  movie-app/src/scss/components/header/_header.scss
  movie-app/src/scss/components/header/_navigation.scss
  movie-app/src/scss/main.scss
  movie-app/src/scss/variables/_colors.scss
Labels: enhancement

#51 Lp 48 modal scroll bar fix
  movie-app/src/scss/components/body/_modal.scss
Labels: bug

#53 Refactor movieGrabber function in Home
  movie-app/src/body/Home.js
  movie-app/src/scss/components/header/_header.scss
Labels: enhancement

#55 feat(movie-card):add-box-shadow-to-movie-cards
  movie-app/src/scss/components/body/_card.scss
Labels: enhancement

#58 typography styling
  movie-app/public/index.html
  movie-app/src/Components/MovieCard.js
  movie-app/src/Components/MovieDetails.js
  movie-app/src/body/Home.js
  movie-app/src/scss/main.scss
  movie-app/src/scss/variables/_typography.scss
Labels: enhancement

#60 Lp 57 input placeholder text
  movie-app/src/header/NavBar.js
Labels: enhancement

#61 Add type parameter to API url to fetch movies only
  movie-app/src/utilities/utils.js
Labels: enhancement

#64 Background issue
  movie-app/src/App.js
  movie-app/src/scss/components/body/_search_results.scss
  movie-app/src/scss/main.scss
Labels: enhancement

#66 Add poster url check for MovieCard and Modal
  movie-app/public/placeholder.svg
  movie-app/src/Components/MovieCard.js
  movie-app/src/Components/MovieDetails.js
Labels: enhancement

#67 Search header
  movie-app/src/App.js
  movie-app/src/body/Searched.js
  movie-app/src/header/NavBar.js
  movie-app/src/scss/main.scss
Labels: enhancement

#69 Changed hero text font size and line height
  movie-app/src/scss/variables/_typography.scss
Labels: enhancement

#71 removed unnecessary package-lock.json outside of app.
  package-lock.json
Labels: enhancement

#72 footer implementation
  .DS_Store
  .github/PULL_REQUEST_TEMPLATE 2.md
  movie-app/src/App.js
  movie-app/src/assets/connie.jpg
  movie-app/src/assets/garrett.jpg
  movie-app/src/assets/kenny.jpg
  movie-app/src/assets/luis.jpg
  movie-app/src/assets/paul.jpeg
  movie-app/src/body/Footer.js
  movie-app/src/scss/components/body/_body.scss
  movie-app/src/scss/components/body/_footer.scss
Labels: enhancement

#75 feat(cursor-hover):pointer-cursor-on-clickable-elements
  movie-app/src/scss/components/body/_card.scss
  movie-app/src/scss/components/body/_modal.scss
  movie-app/src/scss/components/body/_search_results.scss
  movie-app/src/scss/components/header/_searchbar.scss
Labels: enhancement

#80 Make tab friendly
  movie-app/src/Components/MovieCard.js
  movie-app/src/header/NavBar.js
  movie-app/src/scss/main.scss
Labels: enhancement

#81 Replace React favicon and title with ToadTV's
  movie-app/public/favicon.ico
  movie-app/public/favicon.png
  movie-app/public/index.html
  movie-app/src/body/Footer.js
Labels: enhancement

#83 Fixed logo size.
  .DS_Store
  movie-app/public/logo.png
  movie-app/public/logo.svg
Labels: enhancement

#85 Search Bar Bug
  movie-app/src/header/NavBar.js
  movie-app/src/scss/main.scss
Labels: enhancement

#86 footer refactoring and bug fix
  movie-app/src/App.js
  movie-app/src/assets/kermit.gif
  movie-app/src/body/Footer.js
  movie-app/src/body/FooterCard.js
  movie-app/src/scss/components/body/_footer.scss
  movie-app/src/scss/main.scss
Labels: bug, enhancement

#88 Align search text
  movie-app/src/body/Searched.js
  movie-app/src/scss/components/body/_search_results.scss
  movie-app/src/scss/main.scss
Labels: enhancement

#90 feat(modal):Add shadows to different parts of the modal
  movie-app/src/scss/components/body/_modal.scss
Labels: enhancement

#92 Movie Card Info Issue
  movie-app/src/Components/MovieCard.js
Labels: bug
