Repository Lap343/2021-React-Apprenticeship, pull requests merged in 2021-06, with the labels that each got.

#1 docs(issue-templates): add github issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#4 React Setup
  movie-app/.gitignore
  movie-app/README.md
  movie-app/package-lock.json
  movie-app/package.json
  movie-app/public/favicon.ico
  movie-app/public/index.html
  movie-app/public/logo192.png
  movie-app/public/logo512.png
  movie-app/public/manifest.json
  movie-app/public/robots.txt
  movie-app/src/App.css
  movie-app/src/App.js
  movie-app/src/App.test.js
  movie-app/src/index.css
  movie-app/src/index.js
  movie-app/src/logo.svg
  movie-app/src/reportWebVitals.js
  movie-app/src/setupTests.js
  movie-app/yarn.lock
Labels: enhancement

#6 feat(api-call): add functions to get movie by ID and title
  movie-app/.gitignore
  movie-app/src/App.js
  movie-app/src/utilities/utils.js
  movie-app/yarn.lock
Labels: enhancement

#8 feat(movie-card): add a movie card that displays movie info
  movie-app/.gitignore
  movie-app/src/App.css
  movie-app/src/App.js
  movie-app/src/Components/MovieCard.js
  movie-app/src/logo.svg
  movie-app/src/utilities/utils.js
Labels: enhancement

#10 feat(movie-details): add movie detail card
  movie-app/package-lock.json
  movie-app/package.json
  movie-app/src/App.css
  movie-app/src/App.js
  movie-app/src/Components/MovieCard.js
  movie-app/src/Components/MovieDetails.js
  movie-app/src/utilities/utils.js
  movie-app/yarn.lock
Labels: enhancement

#12 refactor(file-structure): change the file structure
  movie-app/src/App.js
  movie-app/src/Components/FeatCarousel.js
  movie-app/src/Components/Modal.js
  movie-app/src/Components/MovieDetails.js
  movie-app/src/Components/StaffCarousel.js
  movie-app/src/body/Home.js
  movie-app/src/body/Searched.js
  movie-app/src/header/NavBar.js
Labels: enhancement

#15 feat(search-page): map through fetched movies data and render it on t…
  README.md
  movie-app/src/App.js
  movie-app/src/Components/MovieCard.js
  movie-app/src/body/Searched.js
  movie-app/src/utilities/utils.js
Labels: enhancement

#16 Installed node-sass@5.0.0. and .scss files for styling
  movie-app/public/logo.svg
  movie-app/public/logo192.png
  movie-app/public/logo512.png
  movie-app/public/manifest.json
  movie-app/src/App.css
  movie-app/src/App.js
  movie-app/src/body/Searched.js
  movie-app/src/header/NavBar.js
  movie-app/src/scss/components/body/_card.scss
  movie-app/src/scss/components/body/_search_results.scss
  movie-app/src/scss/components/header/_header.scss
  movie-app/src/scss/components/header/_searchbar.scss
  movie-app/src/scss/main.scss
  movie-app/src/scss/variables/_colors.scss
  movie-app/src/scss/variables/_typography.scss
  package.json
  yarn.lock
Labels: enhancement

#19 Add styling to MovieCard.
  movie-app/package-lock.json
  movie-app/package.json
  movie-app/src/Components/MovieCard.js
  movie-app/src/body/Searched.js
  movie-app/src/scss/components/body/_card.scss
  movie-app/src/scss/components/body/_search_results.scss
  movie-app/yarn.lock
  package.json
  yarn.lock
Labels: enhancement

#21 Search bar functionality and styling
  movie-app/public/cancel.svg
  movie-app/public/search_icon.svg
  movie-app/src/App.css
  movie-app/src/App.js
  movie-app/src/body/Searched.js
  movie-app/src/header/NavBar.js
  movie-app/src/header/Search_Icon.png
  movie-app/src/scss/components/body/_search_results.scss
  movie-app/src/scss/components/header/_header.scss
  movie-app/src/scss/main.scss
  movie-app/yarn.lock
Labels: enhancement

#23 feat(home-page): Add a home page and style it
  movie-app/src/App.js
  movie-app/src/body/Home.js
  movie-app/src/header/NavBar.js
  movie-app/src/index.js
  movie-app/src/scss/components/body/_search_results.scss
  movie-app/src/utilities/utils.js
  movie-app/yarn.lock
  package-lock.json
Labels: enhancement

#26 feat(search-pagination):adds pagination
  movie-app/public/next.png
  movie-app/src/App.js
  movie-app/src/body/Searched.js
  movie-app/src/scss/components/body/_search_results.scss
  movie-app/src/utilities/utils.js
Labels: enhancement

#27 movie info modal
  movie-app/public/cancel.svg
  movie-app/src/Components/MovieCard.js
  movie-app/src/Components/MovieDetails.js
  movie-app/src/assets/cancel.svg
  movie-app/src/assets/metacritic.png
  movie-app/src/assets/rottentomatoes.png
  movie-app/src/assets/search.svg
  movie-app/src/assets/star.svg
  movie-app/src/body/Searched.js
  movie-app/src/scss/components/body/_body.scss
  movie-app/src/scss/components/body/_modal.scss
  movie-app/src/scss/main.scss
Labels: enhancement

#28 app background styling
  movie-app/public/logo.png
  movie-app/public/logo.svg
  movie-app/src/App.js
  movie-app/src/header/NavBar.js
  movie-app/src/scss/components/body/_body.scss
  movie-app/src/scss/components/body/_search_results.scss
  movie-app/src/scss/components/header/_header.scss
  movie-app/src/scss/main.scss
  movie-app/yarn.lock
Labels: enhancement

#31 Add modal to Home
  movie-app/src/App.js
  movie-app/src/Components/MovieCard.js
  movie-app/src/Components/MovieDetails.js
  movie-app/src/body/Home.js
  movie-app/src/body/Searched.js
Labels: enhancement

#32 search bar styling update
  README.md
  movie-app/src/App.js
  movie-app/src/assets/search 2.svg
  movie-app/src/assets/search-cancel.svg
  movie-app/src/assets/search-magnify.svg
  movie-app/src/header/NavBar.js
  movie-app/src/scss/components/header/_header.scss
  movie-app/src/scss/components/header/_searchbar.scss
  movie-app/src/scss/main.scss
Labels: enhancement

#36 Movie card bug
  movie-app/src/scss/components/body/_card.scss
Labels: bug

#40 Fix gradient background height
  movie-app/src/App.js
  movie-app/src/scss/components/body/_modal.scss
  movie-app/src/scss/main.scss
Labels: enhancement

#41 Search bar functionality
  movie-app/src/App.js
  movie-app/src/header/NavBar.js
Labels: enhancement

#43 Page Navigation Enhancements
  movie-app/src/body/Searched.js
  movie-app/src/header/NavBar.js
  movie-app/src/scss/components/body/_search_results.scss
Labels: enhancement
